### ISSUE TITLE
Anwers in italics are broken when importing

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dthies/moodle-qformat_crossxml#1]
I tried this (nice) plugin with some existing questions. 
The answers that had an italics formatting (see first image) in the original MCQ did not keep the italics, but replaced with underscore characters (second image) in the converted question type:

![mcq italics in answer](https://user-images.githubusercontent.com/2671923/36993270-00059ea2-2073-11e8-9ab9-29d3768a7eb5.png)

![short answer italics in answer broken](https://user-images.githubusercontent.com/2671923/36993280-03d1a404-2073-11e8-8610-3d930eacd147.png)

Excerpt from XML file:
![xml file excerptn](https://user-images.githubusercontent.com/2671923/36993594-e3c307d8-2073-11e8-9028-6fedb09271bf.png)

**Comment by dthies** [comment]
Hello German,
I think this is a limitation of the question type your converting to. If I understand, you are converting from multichoice to shortanswer, multichoice allows any format for answers, but short answer supports only plain text so the html is converted to plain text using PHP html_to_text function. Students can not enter italics in a short answer since it has a text box for entry. It seems in the case of italics it converts to the markdown characters.

**Comment by germanvaleroelizondo** [comment]
Hello Daniel,
Thanks for the explanation.

Would it be very difficult for you to add code in order to check for this and then automatically remove the leading and trailing  _ characters ?

In my University subject (veterinary pathology) departmental quizzes, I have been painstakingly replacing many Multiple Choice questions with short answer questions, because we (the lecturers) realized that our students have become very proficient at **guessing** which of the four available options is the right answer, but they do not really have the knowledge to identify the very important disease signs and lesions that we expect them to learn as future veterinarians.

We have many MC questions where the answers are the scientific names of animal parasites (usually written in italics) and we expect our students to be able to recognize/recall/write these names.

When our students graduate, no animal patient will carry 4 diagnostic or treatment options to choose from. A veterinarian must recall the knowledge and have the abilities to identify and treat the most common animal diseases.  We owe it to the animals.

**Comment by dthies** [comment]
I changed the function used to convert multichoice text. Please check it to make sure it does what you need.

**Comment by germanvaleroelizondo** [comment]
It works beautifully :)

All the MC options of scientific names of parasites are now imported as plain text without the leading and trailing _ characters.

I hope I did not caused you much trouble with this feature request.

Thanks Daniel

**Comment by dthies** [comment]
Thank you for the feedback. It is great to know what real usage situations require.

**Comment by germanvaleroelizondo** [comment]
Once again, thank **you** for helping the teachers who help the students to be better prepared and make a (slightly) better world.
